[package]
name = "nebula-app"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
dirs = { workspace = true }
log = { workspace = true }
nebula-config = { path = "../nebula-config" }
nebula-render = { path = "../nebula-render" }
wgpu = { workspace = true }
winit = { workspace = true }
