[package]
name = "nebula-app"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
dirs = { workspace = true }
log = { workspace = true }
winit = { workspace = true }
