[package]
name = "nebula-math"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
glam = "0.29"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "i128_benchmarks"
harness = false
