[package]
name = "nebula-mesh"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
nebula-voxel = { path = "../nebula-voxel" }
bytemuck = { workspace = true }
static_assertions = { workspace = true }
crossbeam-channel = { workspace = true }
