[package]
name = "nebula-lighting"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
bytemuck = { workspace = true }
glam = { workspace = true }
nebula-voxel = { path = "../nebula-voxel" }
wgpu = { workspace = true }
