[package]
name = "nebula-coords"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
nebula-math = { path = "../nebula-math" }
glam = "0.29"

[dev-dependencies]
trybuild = "1.0"
